### ISSUE TITLE
Compile Optimization Issue

### ISSUE THREAD

**Issue by DaegyuLim** [saga0619/tocabi_avatar#1]
In current simulation version (dyros_tocabi_v2:406df71, mujoco_ros_sim:0730a47), tocabi_avatar package runs very slowly (about 100hz).
I added the compile optimization option (-Ofast) in the CmakeLists and it works well.

add_compile_options(-std=c++17 -Ofast)

**Comment by psh117** [comment]
try

catkin_make -DCMAKE_BUILD_TYPE=RELEASE 
or
catkin build -DCMAKE_BUILD_TYPE=RELEASE
